layout_spectrum: 0.5440188
color:
  saturation: 0.6330881
  lightness: 0.07838795
  brandStrength: 0.8733094
  rhythmicContrast: 0.05006734
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
typography_spectrum: 0.5537057
name: OAthlete
